/**
 * 测试模式会话行:挂在测试模式的 agent.cordis.yml 组合里,随预设的 standing
 * scope 装载一次。两个职责:
 *
 * 1. 向 system-prompt 注册「测试工作流」段:动态插件测试契约(装载→快照→
 *    场景断言→清理断言)是**常驻完整注入**的提示词契约,不是按需加载的技能;
 * 2. 监听 agent/created,当新 agent 的会话以测试模式创建时,确保其工作区
 *    根目录下存在 test-mode/ 目录(「选择测试模式即自动建目录」)。
 *
 * 目录只负责 mkdir:项目文件(用例、套件、结果)由 host 端在 Test 视图或
 * 测试运行时播种,避免两处维护同一份模板。
 * @module @calwang414/dsh-test-mode/preset
 */

import { mkdir } from 'node:fs/promises'
import { join } from 'node:path'

/** 测试模式预设 id:与 .agent-presets 下的目录名一致。 */
export const TEST_MODE_PRESET_ID = 'dsh-test-mode'

/** system-prompt 段名与排序(persona 之后、运行时上下文之前)。 */
export const WORKFLOW_SECTION = 'dsh-test-mode.workflow'
export const WORKFLOW_ORDER = 90

/** 动态插件测试的完整工作流契约(常驻注入)。 */
const TEST_WORKFLOW_TEXT = [
  "",
  "## 测试工作流(测试模式)",
  "",
  "本节是测试模式(共享项目 `{{cwd}}/test-mode/`)的常驻工作流契约,每次测试任务都必须遵守。",
  "",
  "## 共享项目结构",
  "",
  "当前工作区有一个**共享测试项目**,位于 `{{cwd}}/test-mode/` 目录。所有使用测试模式的会话共享它;用户在对话旁的 **Test 视图**中查看与运行测试。",
  "",
  "```text",
  "test-mode/",
  "├── manifests/      被测插件源码与测试套件(每个插件一个子目录)",
  "├── cases/          测试用例(每用例一个 JSON 文件)",
  "├── api/            API 测试(projects/ 项目、environments/ 环境、history.json 执行历史)",
  "├── dbdata/         数据库参考数据(用户导出的表结构与测试数据,见下文)",
  "├── results/        插件测试运行结果(JSON,每轮一次)",
  "└── reports/        执行报告(JSON,每次集合执行一份)",
  "```",
  "",
  "## 动态插件测试契约",
  "",
  "测试对象是**动态 Cordis 插件**(本会话通过 @pluginId 定义或从源码装载的插件)。每个测试套件按三阶段执行:",
  "",
  "1. **装载前快照**:记录基线——`tools.schemas(scope)` 工具清单、目标事件、目标服务存在性;",
  "2. **场景断言**:在被测插件装载后逐条断言——",
  "   - **可见性**:某工具出现在 `tools.schemas(scope)` 中,且 schema 字段精确匹配;",
  "   - **事件**:挂 ctx.on 探针 → 触发事件 → 断言探针收到正确 payload(验证事件通路;插件的业务响应用组合断言验证);",
  "   - **服务**:`ctx.get(name)` 存在,且提供预期方法;",
  "   - **行为**:执行工具,断言返回/错误符合预期;",
  "3. **清理断言**:卸载被测插件后断言——schemas 回到基线、服务回到 undefined(证明副作用随 fiber 销毁,即 HMR 安全;工具/服务断言由场景自动派生,事件监听器是黑盒不做伪验证)。",
  "",
  "## 测试用例管理",
  "",
  "- 用例以 JSON 文件存放在 `test-mode/cases/`,字段:name、description、priority(high/medium/low)、preconditions、steps(数组:action/expected/requestRef/uiRef/data)、tags(只能取标签库 test-mode/tags.json 中的标签,禁止自创)、status(draft/active/archived);",
  "- **步骤可绑定 API 请求或 UI 脚本**:`steps[].requestRef = { projectId, collectionId, requestId }` 或 `steps[].uiRef = { scriptId }`,编辑用例时通过「绑定」下拉选择;混合用例 = UI 操作 + 接口验证编排在同一用例;",
  "- **步骤数据覆盖**:`steps[].data = { url?, body?, query?, headers? }` 可覆盖所绑请求的数据(字段可省,未提供的回退请求配置);**data 的字段结构必须对齐所绑请求在项目文件中的 mock 示例结构**(示例 = 接口测试的参考数据),不要凭空造结构;执行用例时步骤 data 优先于请求配置;",
  "- **执行用例**:`POST /api/cases/:id/run` 按步骤顺序执行绑定的请求与 UI 脚本,变量在步骤间流动,未绑定步骤跳过,结果生成报告;",
  "- **场景用例**:用例 = 一个业务场景(如 注册→登录→下单→退款),步骤按业务顺序编排并绑定真实接口(可跨集合/项目),必要时混入 UI 脚本步骤;AI 一键生成(用例页「AI 生成 · 场景用例」)会先读项目接口与 dbdata 数据参考,再把接口融入用例步骤;不要为了凑接口覆盖而拆分业务场景;",
  "- 写用例前先读现有用例文件,保持结构与命名一致;",
  "- 用例与套件是真实可编辑文件,模型与 Test 视图共用同一存储。",
  "",
  "## API 测试",
  "",
  "- **项目**:`test-mode/api/projects/<id>.json`,字段 name、baseUrl、collections(数组);",
  "- **集合**:项目内的 collections 条目,字段 name、requests(数组);",
  "- **请求**:字段 name、method、url(相对路径拼接 baseUrl,或绝对 URL)、headers、query、body、assertions、extract;",
  "- **环境**:`test-mode/api/environments/<id>.json`,字段 name、variables(对象);「基础配置」视图统一管理,可设为默认环境(存 settings.json),所有执行(API/用例/UI/计划)未指定环境时自动用默认环境;",
  "- **标签库**:`test-mode/tags.json`({ tags: string[] });「基础配置」视图的「标签」页统一管理,用例的 tags 只能从标签库中选择,禁止自创;保存校验会拒绝库外标签;需要新标签时先通过「标签」页添加;",
  "- **数据库参考数据**:`test-mode/dbdata/` 固定目录,存放用户从数据库导出的表结构与测试数据(不直连数据库):`schema.md`(可选,表结构说明)、`<表名>.csv` / `<表名>.md` / `<表名>.xlsx`(测试数据,首行为表头;xlsx 每个 sheet 一张表);生成 mock 测试数据、写用例断言时**优先参考这些数据**(可用 `GET /api/dbdata` 查看已解析的表与样例),保证测试数据与预期贴近真实;数据准确性由导出内容保证,不要臆造表中不存在的记录;",
  "- **变量替换**:请求的 url/headers/query/body 支持占位符变量(形如 VAR,前后双花括号包裹),来源按优先级——请求级 variables > 环境变量;",
  "- **数据工厂(内置)**:占位符 `rand.类型`(形如 `rand.phone`、`rand.email`、`rand.uuid`,前后双花括号包裹)在执行时动态生成测试数据——phone/email/name/idcard/uuid/timestamp/date/number:min:max/string:length;请求配置中的 mock 数据是**接口测试的参考示例**(API 列表执行时使用),也是用例步骤 data 覆盖时必须对齐的结构基准;",
  "- **数据工厂(自定义)**:「数据工厂」视图可配置生成器(key + 模板,模板可嵌套内置 rand 与其他自定义生成器),执行时用 `factory.key` 占位符(前后双花括号包裹)引用;",
  "- **OpenAPI 导入**:`POST /api/import/openapi` 接受 OpenAPI 3.x JSON spec,按 tag 分组自动生成项目集合(OpenAPI 2.0 与 YAML 会拒绝);",
  "- **断言类型**:status(状态码比较)、header(响应头)、body(响应文本)、json(JSON 路径 `$.a.b[0].c`)、duration(耗时上限);",
  "- **变量提取**:请求可声明 extract(响应 JSON 路径 → 变量),供同一集合/用例的后续请求使用;规则支持 `from: 'header'`(从响应头取值,如 set-cookie)与 `export: true`(写入会话缓存);",
  "- **会话变量(登录态复用)**:`test-mode/session.json` 按环境缓存 export 的变量(如 token/cookie);执行前自动合并(会话变量优先于环境变量),执行产生的 export 自动写入——登录接口跑一次,后续集合/用例/计划自动复用,不用重复登录;「基础配置」页环境卡片可查看/清除会话变量;UI 脚本的 eval 步骤可加 `exportAs: '变量名'` 把浏览器里的值(如 localStorage token)写入会话;",
  "- **执行**:`POST /api/run-request` 单请求、`POST /api/run-collection` 整个集合;集合执行自动生成报告写入 `test-mode/reports/`;",
  "- **历史详情**:执行历史保存完整请求/响应,`GET /api/history/:id` 回看。",
  "",
  "## 测试计划",
  "",
  "- 计划 = 一批用例 + 集合 + UI 脚本的一键回归组合,存 `test-mode/plans/<id>.json`:{ id, name, environmentId?, template?, entries, createdAt, updatedAt };id 与文件名一致(小写短横线);environmentId 在创建/编辑计划时绑定,执行时优先使用,未绑定回退默认环境;template: true 表示模板(不可直接执行,只能「从模板新建」);",
  "- entries 条目类型(创建/编辑计划时按需组合):",
  "  - `{kind:'case', caseId}` — caseId 取 test-mode/cases/ 下的文件名;",
  "  - `{kind:'collection', projectId, collectionId}` — 以 test-mode/api/projects/ 下项目文件为准(collectionId 用文件里的 id 或名称);",
  "  - `{kind:'ui', scriptId}` — test-mode/ui/scripts/ 下的文件名;",
  "  - `{kind:'incremental', since, modules?}` — **增量条目**:执行时自动展开「自 since 以来变更的接口/用例/UI 脚本」;since 缺省/空 = 最近一次计划执行时间;modules 填声明的变更模块(标签),按标签自动纳入相关用例;计划文件里**不展开**,报告 entriesSnapshot 存展开快照;",
  "- **增量回归(版本迭代后)**:先读 `test-mode/changelogs/` 的变更清单作为主要信号(见「变更清单」节),再读 test-mode/reports/ 找最近 kind==='plan' 的 createdAt 作 since 兜底;removed 接口不需要测(已删除);",
  "- **全量回归**:entries 覆盖全部集合(collection 条目)或全部场景用例;`POST /api/run-plan` 依次执行全部条目;`failedOnly: true` 只重跑上次失败的条目;",
  "- 创建前先读现有 plans/ 与 projects/cases/ui 目录,引用必须真实存在,禁止捏造 id;写完保存校验报错则修正。",
  "",
  "## 变更清单(迭代增量)",
  "",
  "- 变更清单存 `test-mode/changelogs/<id>.json`,记录一次版本迭代「改了什么」,是增量展开的**语义信号**(比 mtime 精确):{ id, name, version?, source, createdAt, changedRequests: [{ projectId, method, url, change: 'added'|'modified'|'removed' }], changedCases?, changedScripts?, changedElements?, changedTables?, modules?, note? };",
  "- 生成方式:1) **重导 OpenAPI(同名项目)自动 diff** — 新增/修改/删除的接口自动写入清单(source: openapi-diff),更新式导入保留项目 id;2) **AI 从发布说明/用户描述提取** — 用户说「本次改了订单与支付模块」时,按标签体系整理 modules 与 changedCases/changedScripts,写入清单文件(source: ai);3) 手动编辑删除接口时也会自动记录;",
  "- **用例表依赖**:用例可声明 `dependsOn: ['表名']`(test-mode/dbdata/ 下的表),表文件变更时该用例自动纳入增量;",
  "- **用例↔接口覆盖**:步骤绑定 requestRef 后,变更接口会自动带出覆盖它的用例;存量 prose 用例用「AI 生成 · 智能绑定接口」批量补绑;",
  "- **UI 影响面**:元素库元素带 updatedAt,变更元素自动带出引用它的脚本;脚本文件变更直接纳入;",
  "- 写变更清单时:字段结构按上面规范,不要编造接口;removed 的接口若用例仍引用,提示用户清理绑定。",
  "",
  "## UI 自动化(引擎:dsh-cdp-browser)",
  "",
  "- 脚本存 `test-mode/ui/scripts/<id>.json`,步骤:open(导航)、click/type(按元素库引用定位)、press(按键)、assert_text/assert_url/assert_title/assert_element(断言)、eval(任意 JS)、wait、screenshot;",
  "- 元素库存 `test-mode/ui/elements.json`:{ key, selector, page, description },脚本步骤用 `element: <key>` 引用;",
  "- 通过 tools 服务调用 dsh-cdp-browser 的 browser_* 工具驱动受控 Chrome(需该插件已激活);text/url 支持数据工厂占位符;",
  "- 执行:`POST /api/ui/run`,结果写入 `test-mode/reports/`(kind: ui);",
  "- **生成脚本流程(写脚本前必须探测真实页面,禁止凭空猜 selector)**:",
  `  - 先 browser_navigate 打开目标 URL,再用 browser_eval 读取可交互元素,必要时 browser_screenshot 截图确认;`,
  `  - 探测示例:browser_eval 执行 [...document.querySelectorAll('button, a, input, select, textarea')].map(el => ({ tag: el.tagName, text: (el.textContent||'').trim().slice(0,30), id: el.id, name: el.getAttribute('name') })).filter(x => x.text || x.id || x.name),按返回结果挑选稳定定位;`,
  `  - 元素定位优先写入元素库(key + selector),脚本步骤用 element: <key> 引用;定位优先选 id / [data-testid] / label 关联输入框,避免纯文本/位置依赖;`,
  `  - 探测不到的元素:换更稳的定位策略或询问用户,不要编造 selector;`,
  `  - 生成后必须执行验证(POST /api/ui/run),报告全失败 = 定位或步骤错误,按报告修正后重跑,禁止改断言凑通过;`,
  "",
  "## 执行报告",
  "",
  "- 报告存放在 `test-mode/reports/<id>.json`,字段 name、kind(request/case/collection/plan/ui)、summary(total/passed/failed/skipped)、durationMs、results(逐项:pass/status/durationMs/assertions 逐条);",
  "- 执行历史追加在 `test-mode/api/history.json`(保留最近 200 条,含完整请求/响应 detail);",
  "- **迭代期失败归因**(版本迭代后批量失败时,先归因再动手):1) 失败接口出现在变更清单(报告详情有「本版本已变更」徽章)→ 先对比新旧 spec/页面确认**期望是否过期**,期望过期则更新用例/断言,不要当作缺陷汇报;2) 元素定位失败(selector 找不到)→ 用 browser_eval 探测新页面结构,更新元素库,是测试自身过期;3) 都不符合 → 才是真缺陷,引用断言证据汇报;",
  "- 模型汇报执行结果时,引用报告的 summary 与失败请求的断言证据。",
  "",
  "## 产物规范与生成自查",
  "",
  "生成任何测试内容(用例/请求/脚本/计划)前,先读 test-mode/ 对应目录的现有文件,沿用结构与命名。",
  "",
  "### 命名",
  "",
  "- 用例文件:`<项目>-<模块>-<三位序号>-<场景>.json`,如 agenthub-plugins-001-list.json、agenthub-auth-001-login.json;",
  "- 请求/脚本名称用中文短语,动词开头,如「创建插件-默认值」「下载-不存在404」。",
  "",
  "### 最小合法示例",
  "",
  `用例(test-mode/cases/<id>.json):`,
  "",
  `\`\`\`json`,
  `{`,
  `  "name": "登录后获取用户信息",`,
  `  "description": "验证登录接口返回 token 后可访问用户接口",`,
  `  "priority": "high",`,
  `  "preconditions": "服务已启动",`,
  `  "tags": ["登录", "冒烟"],`,
  `  "dependsOn": ["users"],`,
  `  "status": "active",`,
  `  "steps": [`,
  `    { "action": "调用登录接口", "expected": "返回 token", "requestRef": { "projectId": "proj-xxx", "collectionId": "col-auth", "requestId": "req-login" } },`,
  `    { "action": "调用用户接口", "expected": "返回用户信息", "requestRef": { "projectId": "proj-xxx", "collectionId": "col-auth", "requestId": "req-me" } },`,
  `    { "action": "人工核对页面", "expected": "页面展示用户名" }`,
  `  ]`,
  `}`,
  `\`\`\``,
  "",
  `请求(test-mode/api/projects/<id>.json 的 collections[].requests[]):`,
  "",
  `\`\`\`json`,
  `{`,
  `  "id": "req-login",`,
  `  "name": "登录",`,
  `  "method": "POST",`,
  `  "url": "/api/login",`,
  `  "headers": [{ "key": "content-type", "value": "application/json" }],`,
  `  "body": "{\"user\":\"{USER}\"}",`,
  `  "assertions": [`,
  `    { "type": "status", "operator": "eq", "expected": 200 },`,
  `    { "type": "json", "path": "$.token", "operator": "contains", "expected": "tok-" }`,
  `  ],`,
  `  "extract": [{ "name": "TOKEN", "path": "$.token" }]`,
  `}`,
  `\`\`\``,
  "",
  `UI 脚本步骤(test-mode/ui/scripts/<id>.json 的 steps[]):`,
  "",
  `\`\`\`json`,
  `[`,
  `  { "kind": "open", "url": "{BASE_URL}/login" },`,
  `  { "kind": "type", "element": "login-user", "text": "{USER}" },`,
  `  { "kind": "click", "element": "login-submit" },`,
  `  { "kind": "assert_url", "expect": "{BASE_URL}/home" }`,
  `]`,
  `\`\`\``,
  "",
  `计划(test-mode/plans/<id>.json):`,
  "",
  `\`\`\`json`,
  `{`,
  `  "id": "v12-quanliang",`,
  `  "name": "v1.2 全量回归",`,
  `  "environmentId": "local",`,
  `  "entries": [`,
  `    { "kind": "collection", "projectId": "proj-xxx", "collectionId": "col-auth" },`,
  `    { "kind": "incremental", "since": "2026-08-01T00:00:00.000Z" }`,
  `  ]`,
  `}`,
  `\`\`\``,
  "",
  `- 示例中的 {USER}、{BASE_URL} 等是占位符标记:真实文件中写作双花括号形式(占位符名两侧各两个花括号字符),执行时替换为环境变量或数据工厂生成值;`,
  `- 占位符变量的来源只能是环境变量(环境页配置)、内置 rand 生成器或自定义 factory 生成器,禁止编造来源;`,
  `- 保存前先读目标目录现有文件,id 沿用文件内已有值,不自行编造。`,
  "",
  "### 生成后自查(交付前逐条核对)",
  "",
  "- **用例**:name 唯一且符合命名规范;每条用例至少一个带 expected 的步骤;绑定步骤的 requestRef/uiRef 必须指向真实存在的资源——写前先读对应项目/脚本文件核对 id,禁止捏造 id;",
  "- **请求**:method/url 合法;断言 expected 类型正确(status 为数字、json path 以 $ 开头);body 为合法 JSON 或纯文本;禁止凭空捏造接口,只测真实存在的服务;",
  "- **计划**:entries 引用真实存在;增量条目 since 为 ISO 时间或缺省;全量计划覆盖全部集合或场景用例;template:true 的模板不可直接执行;",
  "- **执行验证**:生成后调用执行接口验证(单请求/集合/用例/计划);报告全失败 = 结构或绑定错误,先归因修复;禁止删改断言凑通过;",
  "- **落盘**:所有产物写入 test-mode/ 对应目录,不得只留在对话里;",
  "- **自动提交**:test-mode 文件写盘并通过校验后,插件会自动提交到工作区所在的 git 仓库(仅本次写入的文件,提交信息 `test-mode: <路径> 更新`;仓库缺失/内容无变化时静默跳过)——**不要手动执行 git add/commit 提交 test-mode 数据**,避免重复提交;",
  "",
  "## 工作流",
  "",
  "0. **先读后写**:动手前先读 `test-mode/` 下的 manifests、cases 与现有结果,理解既有测试;",
  "1. **编写被测插件源码**:放在 `test-mode/manifests/<name>/plugin.js`(参考 @pluginId 动态插件的代码风格:纯 JS、ctx.get 读服务、ctx.effect 管副作用);",
  "2. **编写测试套件**:`test-mode/manifests/<name>/suite.json`——断言清单(可见性/事件/服务/行为)+ 场景参数;",
  "3. **运行**:通过 Test 视图或测试运行工具执行,结果写入 `test-mode/results/<name>-<时间戳>.json`;",
  "4. **修复与回归**:清理断言失败 = 副作用泄漏,优先修被测插件的生命周期代码(ctx.effect/ctx.on 返回值);",
  "5. **完成后自查(review)**:每次交付前按以下清单自查——",
  "   - **三阶段齐全**:套件同时含装载前快照、场景断言与清理断言;",
  "   - **断言可执行**:断言引用的事件/服务/工具名在基线快照中可核对;",
  "   - **结果落盘**:运行结果已写入 `test-mode/results/`,不是只留在对话里;",
  "   - **项目共享**:没有把 test-mode/ 下文件写死到别的目录。",
  "",
  "## 约束",
  "",
  "- 只修改 `{{cwd}}/test-mode/` 内的文件;",
  "- 被测插件源码是**测试输入**,不是生产代码——不要把它装进会话或注册成可用工具;",
  "- 测试运行会真实装载被测插件到隔离作用域并卸载,副作用应被清理断言覆盖;",
  "- test-mode/ 被所有测试模式会话共享:保存前先读当前文件,避免覆盖他人的最新修改;",
  "- 保存测试内容(用例/项目/脚本/计划)用 **write/edit 工具**写 `{{cwd}}/test-mode/` 下的文件:写入后会自动执行结构校验,校验失败会以工具失败结果反馈(含具体位置与原因),必须按报错修正后重新写入;通过 bash 等命令写入不会触发自动校验,避免使用;",
  "- 通过 API 保存(用例/项目/计划)同样有结构校验,字段缺失、枚举非法或引用不存在的资源会被 400 拒绝,报错信息包含具体位置,按报错修正后再保存。",
  "",
  "## 能力边界",
  "",
  "- 适合:动态 Cordis 插件的行为与生命周期测试、测试用例管理、API 冒烟与回归、UI 自动化(需 dsh-cdp-browser 激活)、执行报告;",
  "- 不适合:需求分析(后续版本);",
  "- 测试引擎真实执行被测插件代码、真实 HTTP 请求与真实浏览器操作,只用于你信任的源码与目标服务。"
].join('\n')

/**
 * 测试模式会话行插件。
 * @param ctx - standing scope 上下文(组合装载一次,加入的 agent 通过作用域继承)。
 */
export function apply(ctx) {
  ctx.effect(() => ctx.systemPrompt.section({
    name: WORKFLOW_SECTION,
    order: WORKFLOW_ORDER,
    text: TEST_WORKFLOW_TEXT,
  }), 'dsh-test-mode: workflow prompt section')

  ctx.on('agent/created', ({ agent }) => {
    const header = agent?.session?.header
    const cwd = header?.cwd
    if (!cwd || header?.agentPreset !== TEST_MODE_PRESET_ID) return
    void mkdir(join(cwd, 'test-mode'), { recursive: true }).catch((error) => {
      ctx.logger.warn?.(`dsh-test-mode: cannot create test-mode dir under ${cwd}: ${String(error)}`)
    })
  })
}

export const inject = ['systemPrompt']
